[package]
name = "brane-let"
version = { workspace = true }
authors = { workspace = true }
edition = "2018"
rust-version = "1.74.1"

[[bin]]
name = "branelet"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.89"
base64 = "0.22.1"
clap = { version = "4.5.13", features = ["derive","env"] }
dotenvy = "0.15.0"
env_logger = "0.11.5"
libc = "0.2.154"
log = "0.4.22"
reqwest = { version = "0.12.5", features = ["json", "native-tls-vendored"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
serde_yaml = { version = "0.0.10", package = "serde_yml" }
tokio = { version = "1.40.0", features = ["full", "time"] }
tonic = "0.12.3"
yaml-rust = { version = "0.8", package = "yaml-rust2" }

brane-ast = { path = "../brane-ast" }
brane-exe = { path = "../brane-exe" }
brane-oas = { path = "../brane-oas" }
specifications = { path = "../specifications" }
