import test;

test::hello_world();

#[on = "test"]
{
    println("I'm talking to you from far away!");
    test::hello_world();
}

let random := "random";
#[on = random]
{
    println("I have no idea where I am!");
    test::hello_world();
}

func fourty_two() {
    return "42";
}
func hello_world() {
    return test::hello_world();
}

#[on = fourty_two()]
{
    return hello_world();
}



// Obsolete!

// // Test an on-statement
// on "test" {
//     println("I'm talking to you from far away!");
//     hello_world();
// }

// let random := "random";
// on "random_but_not_really_anymore" {
//     println("I have no idea where I am!");
//     hello_world();
// }

// func fourty_two() {
//     return "42";
// }
// on "42" {
//     println("I have found the answer");
//     hello_world();
// }
