#!/bin/bash

shopt -s globstar

ret=0
echo "Running Cargo MSRV on the entire workspace"
for dir in ./brane* specifications overview xtask; do
    echo "::group::${dir}"
    pushd $dir
    if ! cargo msrv verify; then
        ret=1
    fi
    popd
    echo "::endgroup::"
done

exit $ret
