name: Continuous deployment
on:
  pull_request: 
  push:

jobs:
  build-images:
    # Note that we don't depend on check in stable or nightly
    # as code need not compile for the formatter to work
    name: "Documentation"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      # Do we need qemu?
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build time
        run: python ./make.py api-image

