name: Continuous integration
on:
  pull_request: 
  push:

jobs:
  matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable, nightly]

    uses: ./.github/workflows/ci-common.yml
    with:
      os: "${{ matrix.os }}"
      rust-version: "${{ matrix.rust }}"


