name: Continuous integration
on:
  pull_request: 
  push:

jobs:
  msrv:
    # Lets first make sure it works with the most recent version before we attempt all supported versions
    name: "Minimum supported rust version"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Cargo Binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Install Cargo MSRV
        run: cargo binstall --no-confirm cargo-msrv --version ^0.16
      - name: "Run minimum supported rust version"
        run: find . -name Cargo.toml -exec cargo msrv verify --all-features --manifest-path '{}' \;
