name: Continuous integration
on:
  pull_request: 
  push:

jobs:
  check-essential:
    name: "Cargo Check (Stable)"
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
        rust: [stable]

    uses: ./.github/workflows/mixin-cargo-check.yml
    with:
      os: "${{ matrix.os }}"
      rust-version: "${{ matrix.rust }}"

  # This one is optional, but it is nice to know if something will work as intended in the future
  check-nightly:
    name: "Cargo Check (Nightly)"
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
        rust: [nightly]

    uses: ./.github/workflows/mixin-cargo-check.yml
    with:
      os: "${{ matrix.os }}"
      rust-version: "${{ matrix.rust }}"

  test:
    needs: check-essential
    name: "Cargo Test"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        rust: [stable, nightly]

    uses: ./.github/workflows/mixin-cargo-test.yml
    with:
      os: "${{ matrix.os }}"
      rust-version: "${{ matrix.rust }}"

  clippy:
    needs: check-essential
    name: "Cargo Clippy"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    uses: ./.github/workflows/mixin-cargo-clippy.yml
    with:
      os: "${{ matrix.os }}"
      rust-version: "${{ matrix.rust }}"

  # We use the nightly formatter because it has additional formatter settings
  fmt:
    needs: check-essential
    name: "Cargo Fmt"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    uses: ./.github/workflows/mixin-cargo-fmt.yml
    with:
      os: "${{ matrix.os }}"
      rust-version: "${{ matrix.rust }}"

  # Clippy contains more lints in nightly, they might be unstable / unusable, but show them regardless
  clippy-nightly:
    needs: check-nightly
    name: "Cargo Clippy Nightly"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    uses: ./.github/workflows/mixin-cargo-test.yml
    with:
      os: "${{ matrix.os }}"
      rust-version: "${{ matrix.rust }}"
