name: Common Workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      rust-version:
        required: true
        type: string

jobs:
  cargo-check:
    name: Cargo Check (${{ inputs.os }})
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust-version }}
          components: rustfmt, clippy

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: 21.11
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check project
        run: cargo check --workspace

  cargo-test:
    needs: cargo-check
    name: Cargo Test (${{ inputs.os }})
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust-version }}
          components: rustfmt, clippy

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: 21.11
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run unit tests
        run: cargo test --workspace

  cargo-clippy:
    needs: cargo-check
    name: Cargo Clippy (${{ inputs.os }})
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust-version }}
          components: rustfmt, clippy

      - name: Run unit tests
        run: cargo clippy --workspace
