name: Common Workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      rust-version:
        required: true
        type: string

jobs:
  cargo-clippy:
    name: Cargo Clippy (${{ inputs.os }})
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust-version }}
          components: rustfmt, clippy

      - name: Run unit tests
        run: cargo clippy --workspace
