name: Cargo Check

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      rust-version:
        required: true
        type: string

jobs:
  cargo-check:
    name: Cargo Check (${{ inputs.os }})
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust-version }}
          components: rustfmt, clippy

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: 21.11
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: cargo clippy
        uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-check'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: --workspace -- -Dwarnings
